### ISSUE TITLE
Extra column in CSV file, but not in config fails to raise error

### ISSUE THREAD

**Issue by willu47** [OSeMOSYS/otoole#156]
# Set up

`config.yaml`:
```yaml
Test:
    indices: [REGION]
    type: param
    dtype: float
    default: 0.05
```
`data/Test.csv` file:
```
REGION,TECHNOLOGY,VALUE
SIMPLICITY,BLA,0.05
```

# Expected behaviour

After running

    otoole convert csv datafile data test.txt config.yaml

I would expect an error to be raised because the csv file does not match the config.

# Actual behaviour

The command runs successfully. The results datafile contains only the region column. Note that if there are multiple rows, then the region column in this case would contain duplicate values.
