### ISSUE TITLE
[Bug]: Config file `calculated` field not working 

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/otoole#173]
### The Issue

If I set the `calculated` field to `False` in the config file for a result variable, it is still calculated. 

### Expected Behavior

If a variable has the field `Calculated: False`, I would expect the variable not to be calculated. This may be useful if there is a heavy calculation that you dont actually need. 

### Steps To Reproduce

1. Set the field shown below in the config file 

```yaml
Demand:
    indices: [REGION, TIMESLICE, FUEL, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
```

2. Run a results command 
3. View the variable results in the file `results/Demand.csv`

### Log output

```shell
na
```

### Operating System

Linux

### What version of otoole are you running?

1.0.2

### Possible Solution

Should just be able to add in the following loop to the `ReadResults.calcualte_results(..)` method: 

```python 
if not self.results_config[name]["calculated"]:
    LOGGER.info(f"{name} not calculated from config file")
    continue
```
