### ISSUE TITLE
[FEATURE]: Switch to Coveralls Action 

### ISSUE THREAD

**Issue by trevorb1** [OSeMOSYS/otoole#208]
### Feature Request

Coveralls recommends using [their GitHub Action](https://github.com/coverallsapp/github-action) for CI. Currently, we manually upload to coveralls through the following: 

```yaml 
- name: Upload coverage data to converalls.io
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
  run: |
    pip install --upgrade coveralls
    coveralls --service=github
```

### Suggested Solution

Should be something similar to 

```yaml 
- name: Upload coverage data to converalls.io
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
  uses: coverallsapp/github-action@v2
```

### Additional Info

See PR #207 for a minor discussion on this topic
